# Generated by Django 5.1.3 on 2024-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0002_services_specialty_user_doctor_patient_medicalrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
