# Generated by Django 5.1.3 on 2024-11-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0003_doctor_profile_photo_patient_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='service',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='time_start',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='services',
            name='benefit',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='services',
            name='need',
            field=models.TextField(default=''),
        ),
    ]
