# Generated by Django 5.1.3 on 2024-11-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0004_remove_doctor_service_remove_schedule_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Lainya', max_length=255),
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
