# Generated by Django 5.1.3 on 2024-11-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0005_patient_gender_delete_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
