# Generated by Django 5.1.3 on 2024-11-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0006_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Reject', 'Reject')], max_length=10),
        ),
    ]
