# Generated by Django 5.1.3 on 2024-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0008_users_delete_user_remove_doctor_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
    ]
