# Generated by Django 5.1.3 on 2024-11-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0009_doctor_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='username',
            new_name='email',
        ),
    ]
