# Generated by Django 5.1.3 on 2024-11-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0011_users_is_active_users_is_staff_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
