# Generated by Django 5.1.3 on 2024-11-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0013_remove_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
