# Generated by Django 5.1.3 on 2024-11-29 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental', '0014_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Reject', 'Reject')], max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.schedule')),
            ],
        ),
    ]
